# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/adammac8/Desktop/v2017_proc/ece449_processor/2017ver/ece449_processor/ece449_processor.srcs/sources_1/ip/DIST_ROM_1024/DIST_ROM_1024.xci
# IP: The module: 'DIST_ROM_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adammac8/Desktop/v2017_proc/ece449_processor/2017ver/ece449_processor/ece449_processor.srcs/sources_1/ip/DIST_ROM_1024/DIST_ROM_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DIST_ROM_1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/adammac8/Desktop/v2017_proc/ece449_processor/2017ver/ece449_processor/ece449_processor.srcs/sources_1/ip/DIST_ROM_1024/DIST_ROM_1024.xci
# IP: The module: 'DIST_ROM_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/adammac8/Desktop/v2017_proc/ece449_processor/2017ver/ece449_processor/ece449_processor.srcs/sources_1/ip/DIST_ROM_1024/DIST_ROM_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DIST_ROM_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
